apiVersion: v1 #versi API untuk object service.
kind: Service #membuat sebuah service.
metadata: #berisi metadata terkait service.
  name: mongo-service #nama service.
spec: #berisi spesifikasi service.
  selector: #digunakan untuk memilih pod-pod yang akan dipetakan oleh service berdasarkan label.
    app: mongodb #pod-pod dengan label "app: mongodb" akan dipetakan oleh service.
  ports: #mendefinisikan port yang akan dibuka oleh service.
    - protocol: TCP #protocol yang akan digunakan
      port: 27017 #menentukan port yang akan digunakan oleh service.
      targetPort: 27017 #menentukan port di dalam container atau pod yang akan dituju oleh service.
