apiVersion: v1 #versi API untuk object service
kind: Service #membuat sebuah service
metadata: #berisi metadata terkait service
    name: rabbitmq-service #nama service
spec: #berisi spesifikasi service
    selector: #digunakan untuk memilih pod-pod yang akan dipetakan oleh service berdasarkan label
        app: rabbitmq #pod-pod dengan label "app: rabbitmq" akan dipetakan oleh service
    ports: #mendefinisikan port yang akan dibuka oleh service
        - protocol: TCP #protokol yang digunakan oleh Service adalah TCP
          name: tcp-rabbitmq #nama port pada Service ini adalah "tcp-rabbitmq"
          port: 5672 #menentukan port yang akan digunakan oleh service
          targetPort: 5672 #menentukan port di dalam container atau pod yang akan dituju oleh service