apiVersion: apps/v1 #menentukan versi API untuk objek Deployment
kind: Deployment #menandakan bahwa objek ini adalah Deployment
metadata: #berisi metadata untuk Deployment, seperti nama dan label.
    name: order #nama Deployment yang akan dibuat.
spec: #spesifikasi Deployment
    selector: #menentukan selektor untuk memilih Pods yang terkait dengan Deployment ini.
        matchLabels: #selektor yang digunakan untuk memilih objek-objek yang terkait.
            app: order #pods yang memiliki label "app: order" akan dipilih.
    template: #template Pod yang akan digunakan oleh Deployment.
        metadata: #metadata untuk template Pod.
            labels: #list label
                app: order #label untuk template Pod.
        spec: #spesifikasi template Pod.
            containers: #konfigurasi container yang akan dijalankan di dalam Pod.
                - name: order #nama container.
                  image: ghcr.io/adityaayatusy/a433-microservices/order-service:latest #image Docker yang akan digunakan untuk container.
                  ports:
                      - containerPort: 3000 #port yang akan diexpose oleh container.
                  env: #environment yang akan digunakan di container
                      - name: PORT #variable yang akan di set
                        value: "3000" #value yang akan di set
                      - name: AMQP_URL #variable yang akan di set
                        value: "amqp://rabbitmq-service.default.svc.cluster.local:5672" #value yang akan di set berdasarkan dns pada service yang didefine